### ISSUE TITLE
鸣潮签到成功后错误报文

### ISSUE THREAD

**Issue by Ropgrc** [mxyooR/Kuro-autosignin#16]
如标题说的，错误报文如下。是因为没有配置 push.ini 文件吗？

`
2024-12-05 11:32:19 - 开始签到
2024-12-05 11:32:19 - 开始鸣潮签到
2024-12-05 11:32:20 - 今天的奖励为：请求失败，响应代码: 1511, 消息: 请勿重复签到
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    sign_in()
  File "main.py", line 53, in sign_in
    server_message += KuroBBS_sign_in(tokenraw, devcode, distinct_id)
  File "bbs_sgin_in.py", line 167, in KuroBBS_sign_in
    msg = msg+log_message(str(bbssignin(bbsheaders)))+"\n\n"
  File "bbs_sgin_in.py", line 153, in bbssignin
    response = requests.post(urlbbssignin, headers=headers, data=databbs)
  File "venv\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "venv\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "venv\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "venv\lib\site-packages\urllib3\connectionpool.py", line 495, in _make_request
    conn.request(
  File "venv\lib\site-packages\urllib3\connection.py", line 397, in request
    self.putheader(header, value)
  File "venv\lib\site-packages\urllib3\connection.py", line 311, in putheader
    super().putheader(header, *values)
  File "Python\Python310\lib\http\client.py", line 1255, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-3: ordinal not in range(256)
`

config 配置文件
![屏幕截图 2024-12-05 113413](https://github.com/user-attachments/assets/01c825b5-c1b7-4da7-8dd0-d99b87ec3b8f)

config 文件夹
![屏幕截图 2024-12-05 113421](https://github.com/user-attachments/assets/d3193a2f-07f5-4de7-a420-7a29adb68c29)

配置信息是通过 tools.py 获取的。

**Comment by mxyooR** [comment]
devcode没加 config里面的

**Comment by mxyooR** [comment]
disitinct id也要改
![image](https://github.com/user-attachments/assets/ea1ec408-3b27-4397-9521-da42433855b9)

**Comment by Ropgrc** [comment]
> devcode没加config里面的

加了 tool.py 生成的之后还是一样的错误。

**Comment by Ropgrc** [comment]
> disitinct id也要改 ![图像](https://private-user-images.githubusercontent.com/88259089/392647149-ea1ec408-3b27-4397-9521-da42433855b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNzExNDUsIm5iZiI6MTczMzM3MDg0NSwicGF0aCI6Ii84ODI1OTA4OS8zOTI2NDcxNDktZWExZWM0MDgtM2IyNy00Mzk3LTk1MjEtZGE0MjQzMzg1NWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDAzNTQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzOGNkY2JjNmI5NGVhNjkyZmU2MmZkMzIwMTgxM2ZiNjYzZGJmMWViYjM2NjU2OWY0MTA0M2U0Y2M3OTQ0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gn82qDS9t8QLx4aNbG2cazweU9i9uwHqWxB9XNd-JlQ)

这个参数的信息是在哪里获取的？

**Comment by Ropgrc** [comment]
好吧，distinct_id 参数需要留空，问题解决了。

**Comment by mxyooR** [comment]
distinctid可以抓包获取 或者随机生成一串uuid

**Comment by Ropgrc** [comment]
> distinctid可以抓包获取 或者随机生成一串uuid

好的，我记住了。
